# CST371/.github/workflows/demo_workflow.yml
name: First Workflow                                               
on: push                                                  
jobs:                         
  first-job:                           
    name: Say hi                           
    runs-on: macos-latest                          
    steps:                           
    - name: Print a greeting                             
      run: echo Hi from our first workflow!